### ISSUE TITLE
Feature request: Animate on init

### ISSUE THREAD

**Issue by charlatan154** [lazybensch/ember-cli-scrolling-content#1]
Hi, nice work. Can you add an option to animate once while you insert the component into the dom. It would be nice for a quick preview. Thanks.

**Comment by lazybensch** [comment]
Thx for your input @charlatan154! I extended the component for you in a way that you will have full programmatic control over the scrolling. This way you will be able to trigger the animation yourself on DOM insertion, or on click or whatever event you want.

Since github is struggling a bit today i will deploy the new features tomorrow around noon.

Have a great day.

**Comment by lazybensch** [comment]
Implementing an option to animate on DOM insertion seemed a bit too *special case* for me so i now give the user the power to control the scrolling with the `scrollForward` property and to listen to `didScrollForward` and `didScrollBackward` events to execute custom logic. 

You can check out the new features in the guides [advanced section](http://lazybensch.github.io/ember-cli-scrolling-content/#advanced). Especially the last one could be of interest for you as it demonstrates how you can trigger a scroll/scroll-back animation on click. you can use this pattern to trigger an animation once your controller or component rendered.

**Comment by charlatan154** [comment]
wow great, everything worked nicely. One more option that it would be cool is that instead of rolling backwards on mouseout, have an option to quick reset to the beginning(with optional delay maybe). Anyway thanks for your time and your quick response!
